generate-mocks:
	@mockgen --build_flags='--tags=dynamic' -destination=service/repository/mocks/mock_post_repository.go -package=mocks github.com/wnfrx/unit-testing-sharing-session/2-clean-architecture/service PostRepository
